// Code generated by MockGen. DO NOT EDIT.
// Source: rpc/client.go
//
// Generated by this command:
//
//	mockgen -source=rpc/client.go -destination=./rpc/client_mock.go -package rpc
//

// Package rpc is a generated GoMock package.
package rpc

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockInternalClientIface is a mock of InternalClientIface interface.
type MockInternalClientIface struct {
	ctrl     *gomock.Controller
	recorder *MockInternalClientIfaceMockRecorder
	isgomock struct{}
}

// MockInternalClientIfaceMockRecorder is the mock recorder for MockInternalClientIface.
type MockInternalClientIfaceMockRecorder struct {
	mock *MockInternalClientIface
}

// NewMockInternalClientIface creates a new mock instance.
func NewMockInternalClientIface(ctrl *gomock.Controller) *MockInternalClientIface {
	mock := &MockInternalClientIface{ctrl: ctrl}
	mock.recorder = &MockInternalClientIfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInternalClientIface) EXPECT() *MockInternalClientIfaceMockRecorder {
	return m.recorder
}

// SayHello mocks base method.
func (m *MockInternalClientIface) SayHello(ctx context.Context, req *HelloRequest) (*HelloReply, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SayHello", ctx, req)
	ret0, _ := ret[0].(*HelloReply)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SayHello indicates an expected call of SayHello.
func (mr *MockInternalClientIfaceMockRecorder) SayHello(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SayHello", reflect.TypeOf((*MockInternalClientIface)(nil).SayHello), ctx, req)
}

// SendAppendEntries mocks base method.
func (m *MockInternalClientIface) SendAppendEntries(ctx context.Context, req *AppendEntriesRequest) RPCRespWrapper[*AppendEntriesResponse] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendAppendEntries", ctx, req)
	ret0, _ := ret[0].(RPCRespWrapper[*AppendEntriesResponse])
	return ret0
}

// SendAppendEntries indicates an expected call of SendAppendEntries.
func (mr *MockInternalClientIfaceMockRecorder) SendAppendEntries(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendAppendEntries", reflect.TypeOf((*MockInternalClientIface)(nil).SendAppendEntries), ctx, req)
}

// SendRequestVote mocks base method.
func (m *MockInternalClientIface) SendRequestVote(ctx context.Context, req *RequestVoteRequest) chan RPCRespWrapper[*RequestVoteResponse] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendRequestVote", ctx, req)
	ret0, _ := ret[0].(chan RPCRespWrapper[*RequestVoteResponse])
	return ret0
}

// SendRequestVote indicates an expected call of SendRequestVote.
func (mr *MockInternalClientIfaceMockRecorder) SendRequestVote(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendRequestVote", reflect.TypeOf((*MockInternalClientIface)(nil).SendRequestVote), ctx, req)
}

// String mocks base method.
func (m *MockInternalClientIface) String() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "String")
	ret0, _ := ret[0].(string)
	return ret0
}

// String indicates an expected call of String.
func (mr *MockInternalClientIfaceMockRecorder) String() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "String", reflect.TypeOf((*MockInternalClientIface)(nil).String))
}
