// Code generated by MockGen. DO NOT EDIT.
// Source: raft/membership.go

// Package raft is a generated GoMock package.
package raft

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	rpc "github.com/maki3cat/mkraft/rpc"
)

// MockMembershipMgrIface is a mock of MembershipMgrIface interface.
type MockMembershipMgrIface struct {
	ctrl     *gomock.Controller
	recorder *MockMembershipMgrIfaceMockRecorder
}

// MockMembershipMgrIfaceMockRecorder is the mock recorder for MockMembershipMgrIface.
type MockMembershipMgrIfaceMockRecorder struct {
	mock *MockMembershipMgrIface
}

// NewMockMembershipMgrIface creates a new mock instance.
func NewMockMembershipMgrIface(ctrl *gomock.Controller) *MockMembershipMgrIface {
	mock := &MockMembershipMgrIface{ctrl: ctrl}
	mock.recorder = &MockMembershipMgrIfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMembershipMgrIface) EXPECT() *MockMembershipMgrIfaceMockRecorder {
	return m.recorder
}

// GetAllPeerClients mocks base method.
func (m *MockMembershipMgrIface) GetAllPeerClients() ([]rpc.InternalClientIface, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllPeerClients")
	ret0, _ := ret[0].([]rpc.InternalClientIface)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllPeerClients indicates an expected call of GetAllPeerClients.
func (mr *MockMembershipMgrIfaceMockRecorder) GetAllPeerClients() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllPeerClients", reflect.TypeOf((*MockMembershipMgrIface)(nil).GetAllPeerClients))
}

// GetCurrentNodeID mocks base method.
func (m *MockMembershipMgrIface) GetCurrentNodeID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentNodeID")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetCurrentNodeID indicates an expected call of GetCurrentNodeID.
func (mr *MockMembershipMgrIfaceMockRecorder) GetCurrentNodeID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentNodeID", reflect.TypeOf((*MockMembershipMgrIface)(nil).GetCurrentNodeID))
}

// GetMemberCount mocks base method.
func (m *MockMembershipMgrIface) GetMemberCount() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMemberCount")
	ret0, _ := ret[0].(int)
	return ret0
}

// GetMemberCount indicates an expected call of GetMemberCount.
func (mr *MockMembershipMgrIfaceMockRecorder) GetMemberCount() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMemberCount", reflect.TypeOf((*MockMembershipMgrIface)(nil).GetMemberCount))
}

// GetPeerClient mocks base method.
func (m *MockMembershipMgrIface) GetPeerClient(nodeID string) (rpc.InternalClientIface, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPeerClient", nodeID)
	ret0, _ := ret[0].(rpc.InternalClientIface)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPeerClient indicates an expected call of GetPeerClient.
func (mr *MockMembershipMgrIfaceMockRecorder) GetPeerClient(nodeID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPeerClient", reflect.TypeOf((*MockMembershipMgrIface)(nil).GetPeerClient), nodeID)
}

// GracefulShutdown mocks base method.
func (m *MockMembershipMgrIface) GracefulShutdown() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GracefulShutdown")
}

// GracefulShutdown indicates an expected call of GracefulShutdown.
func (mr *MockMembershipMgrIfaceMockRecorder) GracefulShutdown() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GracefulShutdown", reflect.TypeOf((*MockMembershipMgrIface)(nil).GracefulShutdown))
}
