// Code generated by MockGen. DO NOT EDIT.
// Source: mkraft/membership.go
//
// Generated by this command:
//
//	mockgen -source=mkraft/membership.go -destination=./mkraft/membership_mock.go -package mkraft
//

// Package mkraft is a generated GoMock package.
package mkraft

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockMembershipMgrIface is a mock of MembershipMgrIface interface.
type MockMembershipMgrIface struct {
	ctrl     *gomock.Controller
	recorder *MockMembershipMgrIfaceMockRecorder
	isgomock struct{}
}

// MockMembershipMgrIfaceMockRecorder is the mock recorder for MockMembershipMgrIface.
type MockMembershipMgrIfaceMockRecorder struct {
	mock *MockMembershipMgrIface
}

// NewMockMembershipMgrIface creates a new mock instance.
func NewMockMembershipMgrIface(ctrl *gomock.Controller) *MockMembershipMgrIface {
	mock := &MockMembershipMgrIface{ctrl: ctrl}
	mock.recorder = &MockMembershipMgrIfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMembershipMgrIface) EXPECT() *MockMembershipMgrIfaceMockRecorder {
	return m.recorder
}

// GetAllPeerClients mocks base method.
func (m *MockMembershipMgrIface) GetAllPeerClients() ([]InternalClientIface, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllPeerClients")
	ret0, _ := ret[0].([]InternalClientIface)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllPeerClients indicates an expected call of GetAllPeerClients.
func (mr *MockMembershipMgrIfaceMockRecorder) GetAllPeerClients() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllPeerClients", reflect.TypeOf((*MockMembershipMgrIface)(nil).GetAllPeerClients))
}

// GetAllPeerClientsV2 mocks base method.
func (m *MockMembershipMgrIface) GetAllPeerClientsV2() (map[string]InternalClientIface, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllPeerClientsV2")
	ret0, _ := ret[0].(map[string]InternalClientIface)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllPeerClientsV2 indicates an expected call of GetAllPeerClientsV2.
func (mr *MockMembershipMgrIfaceMockRecorder) GetAllPeerClientsV2() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllPeerClientsV2", reflect.TypeOf((*MockMembershipMgrIface)(nil).GetAllPeerClientsV2))
}

// GetAllPeerNodeIDs mocks base method.
func (m *MockMembershipMgrIface) GetAllPeerNodeIDs() ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllPeerNodeIDs")
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllPeerNodeIDs indicates an expected call of GetAllPeerNodeIDs.
func (mr *MockMembershipMgrIfaceMockRecorder) GetAllPeerNodeIDs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllPeerNodeIDs", reflect.TypeOf((*MockMembershipMgrIface)(nil).GetAllPeerNodeIDs))
}

// GetMemberCount mocks base method.
func (m *MockMembershipMgrIface) GetMemberCount() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMemberCount")
	ret0, _ := ret[0].(int)
	return ret0
}

// GetMemberCount indicates an expected call of GetMemberCount.
func (mr *MockMembershipMgrIfaceMockRecorder) GetMemberCount() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMemberCount", reflect.TypeOf((*MockMembershipMgrIface)(nil).GetMemberCount))
}

// GracefulShutdown mocks base method.
func (m *MockMembershipMgrIface) GracefulShutdown() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GracefulShutdown")
}

// GracefulShutdown indicates an expected call of GracefulShutdown.
func (mr *MockMembershipMgrIfaceMockRecorder) GracefulShutdown() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GracefulShutdown", reflect.TypeOf((*MockMembershipMgrIface)(nil).GracefulShutdown))
}
