// Code generated by MockGen. DO NOT EDIT.
// Source: mkraft/log/serde.go
//
// Generated by this command:
//
//	mockgen -source=mkraft/log/serde.go -destination=./mkraft/log/serde_mock.go -package log
//

// Package log is a generated GoMock package.
package log

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRaftSerdeIface is a mock of RaftSerdeIface interface.
type MockRaftSerdeIface struct {
	ctrl     *gomock.Controller
	recorder *MockRaftSerdeIfaceMockRecorder
	isgomock struct{}
}

// MockRaftSerdeIfaceMockRecorder is the mock recorder for MockRaftSerdeIface.
type MockRaftSerdeIfaceMockRecorder struct {
	mock *MockRaftSerdeIface
}

// NewMockRaftSerdeIface creates a new mock instance.
func NewMockRaftSerdeIface(ctrl *gomock.Controller) *MockRaftSerdeIface {
	mock := &MockRaftSerdeIface{ctrl: ctrl}
	mock.recorder = &MockRaftSerdeIfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRaftSerdeIface) EXPECT() *MockRaftSerdeIfaceMockRecorder {
	return m.recorder
}

// BatchDeserialize mocks base method.
func (m *MockRaftSerdeIface) BatchDeserialize(data []byte) ([]*RaftLogEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchDeserialize", data)
	ret0, _ := ret[0].([]*RaftLogEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchDeserialize indicates an expected call of BatchDeserialize.
func (mr *MockRaftSerdeIfaceMockRecorder) BatchDeserialize(data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchDeserialize", reflect.TypeOf((*MockRaftSerdeIface)(nil).BatchDeserialize), data)
}

// BatchSerialize mocks base method.
func (m *MockRaftSerdeIface) BatchSerialize(entries []*RaftLogEntry) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchSerialize", entries)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchSerialize indicates an expected call of BatchSerialize.
func (mr *MockRaftSerdeIfaceMockRecorder) BatchSerialize(entries any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchSerialize", reflect.TypeOf((*MockRaftSerdeIface)(nil).BatchSerialize), entries)
}

// LogDeserialize mocks base method.
func (m *MockRaftSerdeIface) LogDeserialize(data []byte) (*RaftLogEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LogDeserialize", data)
	ret0, _ := ret[0].(*RaftLogEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LogDeserialize indicates an expected call of LogDeserialize.
func (mr *MockRaftSerdeIfaceMockRecorder) LogDeserialize(data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogDeserialize", reflect.TypeOf((*MockRaftSerdeIface)(nil).LogDeserialize), data)
}

// LogSerialize mocks base method.
func (m *MockRaftSerdeIface) LogSerialize(entry *RaftLogEntry) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LogSerialize", entry)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LogSerialize indicates an expected call of LogSerialize.
func (mr *MockRaftSerdeIfaceMockRecorder) LogSerialize(entry any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogSerialize", reflect.TypeOf((*MockRaftSerdeIface)(nil).LogSerialize), entry)
}
