// Code generated by MockGen. DO NOT EDIT.
// Source: mkraft/node/node.go
//
// Generated by this command:
//
//	mockgen -source=mkraft/node/node.go -destination=./mkraft/node/node_mock.go -package node
//

// Package node is a generated GoMock package.
package node

import (
	context "context"
	reflect "reflect"

	utils "github.com/maki3cat/mkraft/mkraft/utils"
	gomock "go.uber.org/mock/gomock"
)

// MockNodeIface is a mock of NodeIface interface.
type MockNodeIface struct {
	ctrl     *gomock.Controller
	recorder *MockNodeIfaceMockRecorder
	isgomock struct{}
}

// MockNodeIfaceMockRecorder is the mock recorder for MockNodeIface.
type MockNodeIfaceMockRecorder struct {
	mock *MockNodeIface
}

// NewMockNodeIface creates a new mock instance.
func NewMockNodeIface(ctrl *gomock.Controller) *MockNodeIface {
	mock := &MockNodeIface{ctrl: ctrl}
	mock.recorder = &MockNodeIfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNodeIface) EXPECT() *MockNodeIfaceMockRecorder {
	return m.recorder
}

// AppendEntryRequest mocks base method.
func (m *MockNodeIface) AppendEntryRequest(req *utils.AppendEntriesInternalReq) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AppendEntryRequest", req)
}

// AppendEntryRequest indicates an expected call of AppendEntryRequest.
func (mr *MockNodeIfaceMockRecorder) AppendEntryRequest(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendEntryRequest", reflect.TypeOf((*MockNodeIface)(nil).AppendEntryRequest), req)
}

// ClientCommand mocks base method.
func (m *MockNodeIface) ClientCommand(req *utils.ClientCommandInternalReq) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ClientCommand", req)
}

// ClientCommand indicates an expected call of ClientCommand.
func (mr *MockNodeIfaceMockRecorder) ClientCommand(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClientCommand", reflect.TypeOf((*MockNodeIface)(nil).ClientCommand), req)
}

// GracefulStop mocks base method.
func (m *MockNodeIface) GracefulStop() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GracefulStop")
}

// GracefulStop indicates an expected call of GracefulStop.
func (mr *MockNodeIfaceMockRecorder) GracefulStop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GracefulStop", reflect.TypeOf((*MockNodeIface)(nil).GracefulStop))
}

// Start mocks base method.
func (m *MockNodeIface) Start(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Start", ctx)
}

// Start indicates an expected call of Start.
func (mr *MockNodeIfaceMockRecorder) Start(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockNodeIface)(nil).Start), ctx)
}

// VoteRequest mocks base method.
func (m *MockNodeIface) VoteRequest(req *utils.RequestVoteInternalReq) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "VoteRequest", req)
}

// VoteRequest indicates an expected call of VoteRequest.
func (mr *MockNodeIfaceMockRecorder) VoteRequest(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VoteRequest", reflect.TypeOf((*MockNodeIface)(nil).VoteRequest), req)
}
